name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      CERTIFICATE_P12: ios_certificate.p12
      CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      KEYCHAIN: build.keychain
      KEYCHAIN_PASSWORD: temp_keychain_pass

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Decode and save certificate
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_P12 }}" | base64 --decode > $CERTIFICATE_P12

      - name: Create a temporary keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
          security set-keychain-settings -lut 21600 "$KEYCHAIN"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN" 

      - name: Import certificate to keychain
        run: |
          security import $CERTIFICATE_P12 \
            -k "$KEYCHAIN" \
            -P "$CERTIFICATE_PASSWORD" \
            -T /usr/bin/codesign \
            -T /usr/bin/security

      - name: List identities in keychain (debug)
        run: |
          security list-keychains
          security find-identity -p codesigning "$KEYCHAIN"

      - name: Set keychain as default
        run: |
          security list-keychains -s "$KEYCHAIN"

      - name: Build (example using xcodebuild)
        run: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourAppScheme -sdk iphoneos -configuration Release build

      - name: Clean up keychain
        if: always()
        run: |
          security delete-keychain "$KEYCHAIN"