name: iOS Build and TestFlight Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Decode certificate and provisioning profile
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision

      - name: Debug decoded certificate
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_P12 }}" 
          file certificate.p12
          openssl pkcs12 -info -in certificate.p12 -nokeys -passin pass:"${{ secrets.IOS_CERTIFICATE_PASSWORD }}"

      - name: Install certificate and provisioning profile
        run: | 
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain 
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build & Upload to TestFlight
        run: bundle exec fastlane ios beta
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}